### ISSUE TITLE
Radarr, Sonarr, Lidarr commands are not  enabled if path and profile are not configured.

### ISSUE THREAD

**Issue by shohart** [shayaantx/botdarr#29]
Readme says that these options are not required and should be already set in radarr/sonarr/lidarr itself, but bot refuses to enable commands unless you set those parameters in properties file. after that it fails with error, pointed in other issue.

**Comment by shayaantx** [comment]
I guess I should update the doc, they are required IF you use radarr, sonarr, lidarr. I left them optional, cause technically you can run the bot without radarr (and its required properties)

There is no way to not configure these since I need to know which profile you want to use.

I'll update readme

**Comment by shohart** [comment]
thank you! Everything is pretty much clear now.

**Comment by shayaantx** [comment]
fyi I updated doc, hope its more clear https://github.com/shayaantx/botdarr/commit/9bdc1d08a999f59ed4f5c063bdbfb52f3ba303ab

let me know if its still not clear
