### ISSUE TITLE
Dropdown instead of listing

### ISSUE THREAD

**Issue by Aerya** [shayaantx/botdarr#75]
Hi,

Have you ever thought about replacing the listing results with a dropdown menu like Requestrr/Doplarr?  Seems to be way easier for the user to browse/select the movie/whatever to add to *arr.

![](https://upandclear.org/content/images/2021/12/2021-12-31-12_13_02-Ferdi---Discord---reqz.png)

![](https://upandclear.org/content/images/2022/05/R8zvq2U.png)

**Comment by shayaantx** [comment]
@Aerya haven't considered, but it would be easy to do.

I however don't want to just copy what other bots tbh. I can add some sort of feature flag for this when I get some time to add it.

**Comment by Aerya** [comment]
I understand (and see) you don't copy/rebrand another bot but I think this feature is easier to read/browse than displaying each movie (or else) in the chan.

**Comment by shayaantx** [comment]
yea I was just testing something and can see how its kinda weird at least from the slash command perspective.

So I'll probably pursue something like this, also fyi you can thumbs up any film, and it will add it as well.

**Comment by shayaantx** [comment]
@Aerya what about something like this specifically for slash commands? This way its easier for someone to just click add me instead of doing any copy/pasting.

I could still pursue a list, but because technically you can configure any max amount of items to show in results, it seems alittle better to not have a giant drop down in those cases.

![image](https://user-images.githubusercontent.com/5449086/169866966-5fe41ee2-a1f1-4ab0-b34e-706824ea7324.png)

**Comment by Aerya** [comment]
This button would be great yeah. Seems really easier to add movies than cp the !movie id add xxxx command. And also a bit "faster" than adding a thumbup/+1.

**Comment by shayaantx** [comment]
@Aerya I pushed the add button stuff for radarr, sonarr, lidarr (for discord slash commands only) to 5.4.0-experimental if you wanna check it out.

I'll probably finish the PR at somepoint today or 2moro

**Comment by PrivatePasta** [comment]
I would like to reopen this issue because a dropdown would look much better than separate embeds imho. What Doplarr does is very good, but you could probably do something like SIMLK does too like this:

![](https://cdn.upload.systems/uploads/9W5iKQkD.png)

Or you can use pagination with the new buttons:

![](https://cdn.upload.systems/uploads/CUuKvxpV.png)

Both of these methods are better than the current way of listing all the results as separate embeds. If I search for John Wick, I get almost 20 results that goes on for so long because of the size of the embeds. The problem is not the number of results returned (which I know can be controlled). If you changed how the embed works, you could have as many results as you want without the current amount of clutter.
